stages:
  - test
  - deploy

variables:
  PROJECT_DIR: "insta_follow"
  PROJECT_ABR: "instaflw"

test:
  stage: test
  before_script:
    - cp /var/www/$PROJECT_DIR/project/.env $CI_PROJECT_DIR/
    - virtualenv $CI_PROJECT_DIR/venv 
    - source $CI_PROJECT_DIR/venv/bin/activate
    - pip install -r /var/www/$PROJECT_DIR/project/requirements.txt
  script:
    # - cd $CI_PROJECT_DIR 
    # - pwd
    # - export
    - pip install -r requirements.txt
    - python manage.py check
  after_script:
    - rm $CI_PROJECT_DIR/.env
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $MONBRANCH

staging:
  stage: deploy
  script:
    - echo $PROJECT_DIR
    # - git pull origin develop
    # - uwsgi --reload /tmp/$PROJECT_DIR-master.pid
    # - supervisorctl restart $PROJECT_ABR:*
  only:
    - develop

production:
  stage: deploy
  script:
    - echo $PROJECT_DIR
  only:
    - master
    # - tags
