stages:
  - build
  - test
  - deploy

variables:
  PROJECT_DIR: "insta_follow"

.build:
  stage: build
  script:
    - virtualenv --prompt='($PROJECT_DIR)' -q venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - venv/
    policy: push
  only:
    refs:
      - develop
      - master
    changes:
      - requirements.txt

build_staging:
  extends: .build
  tags:
    - staging

build_production:
  extends: .build
  tags:
    - production

.test:
  stage: test
  before_script:
    - cp /var/www/$PROJECT_DIR/project/.env $CI_PROJECT_DIR/
  script:
    - source $CI_PROJECT_DIR/venv/bin/activate
    - python manage.py check
  after_script:
    - rm $CI_PROJECT_DIR/.env
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - venv/
    policy: pull
  only:
    - develop
    - master

test_staging:
  extends: .test
  tags:
    - staging

test_production:
  extends: .test
  tags:
    - production

.deploy:
  stage: deploy
  before_script:
    - cd /var/www/$PROJECT_DIR/project/
    - source /var/www/$PROJECT_DIR/venv/bin/activate
  script:
    - git pull
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py collectstatic --noinput
    - python manage.py compilemessages
    - uwsgi --reload /tmp/$PROJECT_DIR-master.pid
    - supervisorctl restart $PROJECT_DIR:*
  only:
    - develop
    - master

deploy_staging:
  extends: .deploy
  tags:
    - staging

deploy_production:
  extends: .deploy
  tags:
    - production
#  only:
#    - /^release-.*$/
#    except:
#      - branches