stages:
  - test
#  - migrate
  - deploy

variables:
  PROJECT_DIR: "insta_follow"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - $CI_PROJECT_DIR/venv

.tests:
  stage: test
  before_script:
    - cp /var/www/$PROJECT_DIR/project/.env $CI_PROJECT_DIR/
    - virtualenv $CI_PROJECT_DIR/venv
    - source $CI_PROJECT_DIR/venv/bin/activate
  script:
#    - pip install --no-cache-dir -r requirements.txt
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py check
  after_script:
    - rm $CI_PROJECT_DIR/.env
  tags:
    - django

staging test:
  extends: .tests
  only:
    - develop

production test:
  extends: .tests
  only:
    - master

#migrate:
#  stage: migrate
#  before_script:
#    - cp /var/www/$PROJECT_DIR/project/.env $CI_PROJECT_DIR/
#    - virtualenv $CI_PROJECT_DIR/venv
#    - source $CI_PROJECT_DIR/venv/bin/activate
#  script:
#    - python manage.py makemigrations
#  after_script:
#    - rm $CI_PROJECT_DIR/.env
#  only:
#    changes:
#      - apps/*/models.py
#  tags:
#    - django
#    - staging

staging:
  stage: deploy
  variables:
    PROJECT_ABR: "instaflw"
  before_script:
    - cd /var/www/$PROJECT_DIR/project/
    - source /var/www/$PROJECT_DIR/venv/bin/activate
  script:
    - git pull
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
    - uwsgi --reload /tmp/$PROJECT_DIR-master.pid
    - supervisorctl restart $PROJECT_ABR:*
  only:
    - develop
  tags:
    - django
    - staging

production:
  stage: deploy
  variables:
    PROJECT_ABR: "instaflw"
  before_script:
    - cd /var/www/$PROJECT_DIR/project/
    - source /var/www/$PROJECT_DIR/venv/bin/activate
  script:
    - git pull
    - pip install -r requirements.txt
    - python manage.py migrate
    - uwsgi --reload /tmp/$PROJECT_DIR-master.pid
    - supervisorctl restart $PROJECT_ABR:*
  only:
    - master
    - tags
  tags:
    - django
    - release
