stages:
  - test
  - migrate
  - deploy

variables:
  PROJECT_DIR: "insta_follow"
  PROJECT_ABR: "instaflw"

test:
  stage: test
  variables:
    BRANCH: $CI_COMMIT_REF_NAME
  before_script:
    - cp /var/www/$PROJECT_DIR/project/.env $CI_PROJECT_DIR/
    - virtualenv $CI_PROJECT_DIR/venv 
    - source $CI_PROJECT_DIR/venv/bin/activate
  script:
    # - cd $CI_PROJECT_DIR 
    # - pwd
    - export
    - pip install --no-cache-dir -r requirements.txt
    - python manage.py check
  after_script:
    - rm $CI_PROJECT_DIR/.env
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $RELEASE

migrate:
  stage: migrate
  before_script:
#    - cp /var/www/$PROJECT_DIR/project/.env $CI_PROJECT_DIR/
#    - source $CI_PROJECT_DIR/venv/bin/activate
  script:
    - export
#    - python manage.py makemigrations
#    - python manage.py check
  after_script:
    - rm $CI_PROJECT_DIR/.env
  only:
    variables:
      - $BRANCH == "develop"

staging:
  stage: deploy
  before_script:
    - source /var/www/$PROJECT_DIR/venv/bin/activate
  script:
    - export
    # - git pull origin develop
    # - pip install -r requirements.txt
    # - python manage.py makemigrations
    # - python manage.py migrate
    # - uwsgi --reload /tmp/$PROJECT_DIR-master.pid
    # - supervisorctl restart $PROJECT_ABR:*
  only:
    - develop

production:
  stage: deploy
  script:
    - export
  only:
   - master
    # - tags
